[workspace]

members = [
	"ica_v1/gds",
	"ica_v1/ens",
	"ica_v1/tes",
	"ica_v1/wes",
	"ica_v1/console",
	"ica_v2"
]
exclude = [ "ica_v1/examples/list_gds_volumes", "ica_v1/examples/get_presigned_url" ]
