/*
 * Workflow Execution Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SucceedWorkflowSignalRequest {
    /// External result of a successful signal. Must resolve to a JSON value.
    #[serde(rename = "result", skip_serializing_if = "Option::is_none")]
    pub result: Option<serde_json::Value>,
}

impl SucceedWorkflowSignalRequest {
    pub fn new() -> SucceedWorkflowSignalRequest {
        SucceedWorkflowSignalRequest { result: None }
    }
}
