/*
 * Workflow Execution Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

/// WorkflowVersion : Details of a Workflow version definition

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WorkflowVersion {
    /// Unique resource ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// URN of the resource
    #[serde(rename = "urn", skip_serializing_if = "Option::is_none")]
    pub urn: Option<String>,
    /// HREF to the resource
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    /// Name of the workflow version
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Category of the workflow version
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Description of the workflow version
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<Box<crate::models::WorkflowLanguage>>,
    /// Published Status of the workflow version
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Client ID of the Origin Request
    #[serde(rename = "createdByClientId", skip_serializing_if = "Option::is_none")]
    pub created_by_client_id: Option<String>,
    /// Definition of the workflow version
    #[serde(rename = "definition", skip_serializing_if = "Option::is_none")]
    pub definition: Option<String>,
    /// Time (in UTC) the resource was created
    #[serde(rename = "timeCreated", skip_serializing_if = "Option::is_none")]
    pub time_created: Option<String>,
    /// Time (in UTC) the resource was modified
    #[serde(rename = "timeModified", skip_serializing_if = "Option::is_none")]
    pub time_modified: Option<String>,
    /// User that created the resource
    #[serde(rename = "createdBy", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    /// User that modified the resource
    #[serde(rename = "modifiedBy", skip_serializing_if = "Option::is_none")]
    pub modified_by: Option<String>,
    /// Tenant ID the resource belongs to
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    /// Access control list of the resource
    #[serde(rename = "acl", skip_serializing_if = "Option::is_none")]
    pub acl: Option<Vec<String>>,
}

impl WorkflowVersion {
    /// Details of a Workflow version definition
    pub fn new() -> WorkflowVersion {
        WorkflowVersion {
            id: None,
            urn: None,
            href: None,
            version: None,
            category: None,
            description: None,
            language: None,
            status: None,
            created_by_client_id: None,
            definition: None,
            time_created: None,
            time_modified: None,
            created_by: None,
            modified_by: None,
            tenant_id: None,
            acl: None,
        }
    }
}
