/*
 * Workflow Execution Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WorkflowConnection : Defines a connection that can be used in a workflow definition to perform actions



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WorkflowConnection {
    #[serde(rename = "name")]
    pub name: String,
    /// Type of the connection: PlatformJwt, ApiBearerToken, AwsCredentials, ApiCustomAuthentication, BsshOAuthV2
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    /// For API based connections, the Host part of the API endpoint
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// Regex that hosts associated with this connection must meet (when host override by each run is allowed)
    #[serde(rename = "hostValidationRegex", skip_serializing_if = "Option::is_none")]
    pub host_validation_regex: Option<String>,
    /// Credentials associated with the connection. Format depends on type of connection.
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<String>,
    /// Comma separated list of options associated with the connection: CredentialsRequired, AllowCredentialsOverride, AutoDisableCredentialsAfterUse, AllowHostOverride
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<String>,
    /// Relative URL (relative to Host) to call in order to disable the credentials
    #[serde(rename = "autoDisableUrl", skip_serializing_if = "Option::is_none")]
    pub auto_disable_url: Option<String>,
    /// Http method to use to disable the credentials. Must be POST, PUT or DELETE
    #[serde(rename = "autoDisableHttpMethod", skip_serializing_if = "Option::is_none")]
    pub auto_disable_http_method: Option<String>,
}

impl WorkflowConnection {
    /// Defines a connection that can be used in a workflow definition to perform actions
    pub fn new(name: String) -> WorkflowConnection {
        WorkflowConnection {
            name,
            _type: None,
            host: None,
            host_validation_regex: None,
            credentials: None,
            options: None,
            auto_disable_url: None,
            auto_disable_http_method: None,
        }
    }
}


