/*
 * Workflow Execution Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

/// WorkflowArgument : Argument definition

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WorkflowArgument {
    /// Name of the argument key
    #[serde(rename = "name")]
    pub name: String,
    /// A simple string value for the argument. Cannot provide both Value and Json at the same time.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// A JSON value for the argument. Cannot provide both Value and Json at the same time.
    #[serde(rename = "json", skip_serializing_if = "Option::is_none")]
    pub json: Option<serde_json::Value>,
    /// Comma separated list of options for the argument: Required, Overridable, Writable, Json, Optional, ReadOnly, Final  Some combinations of options are considered errors, like Required/Optional, Overridable/Final, Writable/ReadOnly, etc.
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<String>,
}

impl WorkflowArgument {
    /// Argument definition
    pub fn new(name: String) -> WorkflowArgument {
        WorkflowArgument {
            name,
            value: None,
            json: None,
            options: None,
        }
    }
}
