/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkFileUpdateResponse {
    /// Items failed to be updated with error details
    #[serde(rename = "itemsFailed", skip_serializing_if = "Option::is_none")]
    pub items_failed: Option<Vec<crate::models::BulkUpdateFailedItem>>,
    /// Total items successfully updated
    #[serde(rename = "itemsUpdatedCount", skip_serializing_if = "Option::is_none")]
    pub items_updated_count: Option<i32>,
    /// Total items failed to be updated
    #[serde(rename = "itemsFailedCount", skip_serializing_if = "Option::is_none")]
    pub items_failed_count: Option<i32>,
}

impl BulkFileUpdateResponse {
    pub fn new() -> BulkFileUpdateResponse {
        BulkFileUpdateResponse {
            items_failed: None,
            items_updated_count: None,
            items_failed_count: None,
        }
    }
}
