/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateVolumeConfigurationRequest {
    /// Name for the volume configuration
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "objectStoreSettings")]
    pub object_store_settings: Box<crate::models::ObjectStoreSettings>,
}

impl CreateVolumeConfigurationRequest {
    pub fn new(name: String, object_store_settings: crate::models::ObjectStoreSettings) -> CreateVolumeConfigurationRequest {
        CreateVolumeConfigurationRequest {
            name,
            object_store_settings: Box::new(object_store_settings),
        }
    }
}


