/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

/// CreateFileRequest : CreateFileRequest Model

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateFileRequest {
    /// Name of the file to be uploaded, case sensitive.
    #[serde(rename = "name")]
    pub name: String,
    /// Volume ID to which the file will be uploaded
    #[serde(rename = "volumeId", skip_serializing_if = "Option::is_none")]
    pub volume_id: Option<String>,
    /// Optional folder path where the file will be uploaded to
    #[serde(rename = "folderPath", skip_serializing_if = "Option::is_none")]
    pub folder_path: Option<String>,
    /// Optional file content type, e.g. text/plain, application/json
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    /// Name of the Volume
    #[serde(rename = "volumeName", skip_serializing_if = "Option::is_none")]
    pub volume_name: Option<String>,
    /// The File's Format
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    /// The File's Edam Format
    #[serde(rename = "formatEdam", skip_serializing_if = "Option::is_none")]
    pub format_edam: Option<String>,
    /// Metadata about this file and its contents
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<serde_json::Value>,
}

impl CreateFileRequest {
    /// CreateFileRequest Model
    pub fn new(name: String) -> CreateFileRequest {
        CreateFileRequest {
            name,
            volume_id: None,
            folder_path: None,
            _type: None,
            volume_name: None,
            format: None,
            format_edam: None,
            metadata: None,
        }
    }
}
