/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FileStatus {
    #[serde(rename = "Partial")]
    Partial,
    #[serde(rename = "Available")]
    Available,
    #[serde(rename = "Archived")]
    Archived,
    #[serde(rename = "Unarchiving")]
    Unarchiving,

}

impl ToString for FileStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Partial => String::from("Partial"),
            Self::Available => String::from("Available"),
            Self::Archived => String::from("Archived"),
            Self::Unarchiving => String::from("Unarchiving"),
        }
    }
}

impl Default for FileStatus {
    fn default() -> FileStatus {
        Self::Partial
    }
}




