/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

/// FileArchiveRequest : FileArchiveRequest to specify the Storage Tier

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileArchiveRequest {
    #[serde(rename = "storageTier")]
    pub storage_tier: crate::models::FileArchiveStorageTier,
}

impl FileArchiveRequest {
    /// FileArchiveRequest to specify the Storage Tier
    pub fn new(storage_tier: crate::models::FileArchiveStorageTier) -> FileArchiveRequest {
        FileArchiveRequest { storage_tier }
    }
}
