/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

/// FileUploadCompleteRequest : FileUploadCompleteRequest

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileUploadCompleteRequest {
    /// The multipart upload id used by the object store
    #[serde(rename = "multipartUploadId", skip_serializing_if = "Option::is_none")]
    pub multipart_upload_id: Option<String>,
    /// etags for each uploaded part (optional for files that uses multipart upload)
    #[serde(rename = "partEtags", skip_serializing_if = "Option::is_none")]
    pub part_etags: Option<Vec<crate::models::PartEtag>>,
}

impl FileUploadCompleteRequest {
    /// FileUploadCompleteRequest
    pub fn new() -> FileUploadCompleteRequest {
        FileUploadCompleteRequest {
            multipart_upload_id: None,
            part_etags: None,
        }
    }
}
