/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// FolderArchiveRequest : FolderArchiveRequest to specify the Storage Tier



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FolderArchiveRequest {
    #[serde(rename = "storageTier")]
    pub storage_tier: crate::models::FolderArchiveStorageTier,
}

impl FolderArchiveRequest {
    /// FolderArchiveRequest to specify the Storage Tier
    pub fn new(storage_tier: crate::models::FolderArchiveStorageTier) -> FolderArchiveRequest {
        FolderArchiveRequest {
            storage_tier,
        }
    }
}


