/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VolumeFileListResponse {
    /// Retrieved files
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::FileResponse>>,
    /// Number of items that succeeded
    #[serde(rename = "itemSuccessCount", skip_serializing_if = "Option::is_none")]
    pub item_success_count: Option<i32>,
    /// Number of items that failed
    #[serde(rename = "itemFailedCount", skip_serializing_if = "Option::is_none")]
    pub item_failed_count: Option<i32>,
    /// Item failures with error details
    #[serde(rename = "itemsFailed", skip_serializing_if = "Option::is_none")]
    pub items_failed: Option<Vec<crate::models::BulkFailedItem>>,
}

impl VolumeFileListResponse {
    pub fn new() -> VolumeFileListResponse {
        VolumeFileListResponse {
            items: None,
            item_success_count: None,
            item_failed_count: None,
            items_failed: None,
        }
    }
}
