/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VolumeConfigurationOnlineStatus : The valid Online Status values for Volume configurations in GDS

/// The valid Online Status values for Volume configurations in GDS
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VolumeConfigurationOnlineStatus {
    #[serde(rename = "Initializing")]
    Initializing,
    #[serde(rename = "Ok")]
    Ok,
    #[serde(rename = "Error")]
    Error,

}

impl ToString for VolumeConfigurationOnlineStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Initializing => String::from("Initializing"),
            Self::Ok => String::from("Ok"),
            Self::Error => String::from("Error"),
        }
    }
}

impl Default for VolumeConfigurationOnlineStatus {
    fn default() -> VolumeConfigurationOnlineStatus {
        Self::Initializing
    }
}




