/*
 * Event Notification Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DeliveryTargetAwsSqsQueue : Configuration for an AWS SQS delivery queue



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeliveryTargetAwsSqsQueue {
    /// URL for the AWS SQS queue
    #[serde(rename = "queueUrl")]
    pub queue_url: String,
}

impl DeliveryTargetAwsSqsQueue {
    /// Configuration for an AWS SQS delivery queue
    pub fn new(queue_url: String) -> DeliveryTargetAwsSqsQueue {
        DeliveryTargetAwsSqsQueue {
            queue_url,
        }
    }
}


