/*
 * Event Notification Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DeliveryTargetWorkflowRunLaunch : Configuration for a delivery via WES workflow run launch



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeliveryTargetWorkflowRunLaunch {
    /// Id of the workflow to launch
    #[serde(rename = "id")]
    pub id: String,
    /// Version of the workflow to launch, for the given id
    #[serde(rename = "version")]
    pub version: String,
    /// Name for the workflowRun
    #[serde(rename = "name")]
    pub name: String,
    /// Arguments for the workflowRun
    #[serde(rename = "input", skip_serializing_if = "Option::is_none")]
    pub input: Option<serde_json::Value>,
}

impl DeliveryTargetWorkflowRunLaunch {
    /// Configuration for a delivery via WES workflow run launch
    pub fn new(id: String, version: String, name: String) -> DeliveryTargetWorkflowRunLaunch {
        DeliveryTargetWorkflowRunLaunch {
            id,
            version,
            name,
            input: None,
        }
    }
}


