/*
 * Event Notification Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

/// ErrorResponse : Details for an error which occurred

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// Error code which uniquely identifies the type of error which occurred
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Description of the error which occurred
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Additional details for conditions which caused the error
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<Vec<serde_json::Value>>,
}

impl ErrorResponse {
    /// Details for an error which occurred
    pub fn new() -> ErrorResponse {
        ErrorResponse {
            code: None,
            message: None,
            details: None,
        }
    }
}
