/*
 * Event Notification Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SubscriptionListSortFields {
    #[serde(rename = "id")]
    Id,

}

impl ToString for SubscriptionListSortFields {
    fn to_string(&self) -> String {
        match self {
            Self::Id => String::from("id"),
        }
    }
}

impl Default for SubscriptionListSortFields {
    fn default() -> SubscriptionListSortFields {
        Self::Id
    }
}




