/*
 * Task Execution Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateTaskRunRequest {
    /// User-defined name of the task run
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// User-defined description of the task run
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Access Control List
    #[serde(rename = "acl", skip_serializing_if = "Option::is_none")]
    pub acl: Option<Vec<String>>,
    #[serde(rename = "execution", skip_serializing_if = "Option::is_none")]
    pub execution: Option<Box<crate::models::Execution>>,
}

impl CreateTaskRunRequest {
    pub fn new() -> CreateTaskRunRequest {
        CreateTaskRunRequest {
            name: None,
            description: None,
            acl: None,
            execution: None,
        }
    }
}
