/*
 * Developer Console Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

/// AccessTokenRequest : Access token passed into an api request

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccessTokenRequest {
    /// This is either a psToken or a JWT token depending on the context of the call.
    #[serde(rename = "access_token", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
}

impl AccessTokenRequest {
    /// Access token passed into an api request
    pub fn new() -> AccessTokenRequest {
        AccessTokenRequest { access_token: None }
    }
}
