/*
 * Developer Console Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PeriodUsageSummary {
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
    #[serde(rename = "iCredit", skip_serializing_if = "Option::is_none")]
    pub i_credit: Option<i32>,
    #[serde(rename = "totalUsages", skip_serializing_if = "Option::is_none")]
    pub total_usages: Option<Vec<crate::models::ProductUsage>>,
    #[serde(
        rename = "userAggregatedUsages",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_aggregated_usages: Option<Vec<crate::models::UserAggregatedUsage>>,
}

impl PeriodUsageSummary {
    pub fn new() -> PeriodUsageSummary {
        PeriodUsageSummary {
            start: None,
            end: None,
            i_credit: None,
            total_usages: None,
            user_aggregated_usages: None,
        }
    }
}
