/*
 * Developer Console Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

/// TokenResponse : Response payload for token create

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TokenResponse {
    /// The returned token is either a psToken or a JWT token depending on the context of the call.
    #[serde(rename = "access_token", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
    /// The type of token requested.
    #[serde(rename = "token_type", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<String>,
}

impl TokenResponse {
    /// Response payload for token create
    pub fn new() -> TokenResponse {
        TokenResponse {
            access_token: None,
            token_type: None,
        }
    }
}
