/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

/// FileUnarchiveRequest : FileUnarchiveRequest to specify the RestoreSpeed

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileUnarchiveRequest {
    /// The desired Restore Speed to move the File to the Standard Storage Tier. Valid values are Economy and Standard.
    #[serde(rename = "restoreSpeed")]
    pub restore_speed: String,
}

impl FileUnarchiveRequest {
    /// FileUnarchiveRequest to specify the RestoreSpeed
    pub fn new(restore_speed: String) -> FileUnarchiveRequest {
        FileUnarchiveRequest { restore_speed }
    }
}
