/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * Generated by: https://openapi-generator.tech
 */

/// FolderDeleteOperationParameters : Operation parameters for folder delete operations

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FolderDeleteOperationParameters {
    /// The Urn of the folder for the delete operation
    #[serde(rename = "folderUrn", skip_serializing_if = "Option::is_none")]
    pub folder_urn: Option<String>,
}

impl FolderDeleteOperationParameters {
    /// Operation parameters for folder delete operations
    pub fn new() -> FolderDeleteOperationParameters {
        FolderDeleteOperationParameters { folder_urn: None }
    }
}
