/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JobOperationType : The valid job operation type values for resources in GDS

/// The valid job operation type values for resources in GDS
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobOperationType {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "FolderArchive")]
    FolderArchive,
    #[serde(rename = "FolderUnarchive")]
    FolderUnarchive,
    #[serde(rename = "FolderDelete")]
    FolderDelete,
    #[serde(rename = "FolderCopy")]
    FolderCopy,

}

impl ToString for JobOperationType {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("Unknown"),
            Self::FolderArchive => String::from("FolderArchive"),
            Self::FolderUnarchive => String::from("FolderUnarchive"),
            Self::FolderDelete => String::from("FolderDelete"),
            Self::FolderCopy => String::from("FolderCopy"),
        }
    }
}

impl Default for JobOperationType {
    fn default() -> JobOperationType {
        Self::Unknown
    }
}




