/*
 * Genomic Data Store Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SessionStatus {
    #[serde(rename = "Open")]
    Open,
    #[serde(rename = "Closed")]
    Closed,
    #[serde(rename = "Completed")]
    Completed,
    #[serde(rename = "CompletedWithError")]
    CompletedWithError,

}

impl ToString for SessionStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Open => String::from("Open"),
            Self::Closed => String::from("Closed"),
            Self::Completed => String::from("Completed"),
            Self::CompletedWithError => String::from("CompletedWithError"),
        }
    }
}

impl Default for SessionStatus {
    fn default() -> SessionStatus {
        Self::Open
    }
}




